export const userActionsTypes = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  PROFILE_REQUEST: 'USERS_PROFILE_REQUEST',
  PROFILE_SUCCESS: 'USERS_PROFILE_SUCCESS',
  PROFILE_FAILURE: 'USERS_PROFILE_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
};

export const jobsActionTypes = {
  JOBS_LIST_REQUEST: 'JOBS_LIST_REQUEST',
  JOBS_LIST_LOADED: 'JOBS_LIST_LOADED',
  JOBS_LIST_LOAD_FAILED: 'JOBS_LIST_LOAD_FAILED',
  JOBS_DETAILS_LOADED: 'JOBS_DETAILS_LOADED',
  JOBS_DETAILS_LOAD_FAILED: 'JOBS_DETAILS_LOAD_FAILED',
  JOBS_DETAILS_LOAD_REQUESTED: 'JOBS_DETAILS_LOAD_REQUESTED',

};

export const alertActionsTypes = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  HIDE: 'ALERT_HIDE'
};
