export const userActionsTypes = {
  USERS_REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  USERS_REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  USERS_REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  USERS_LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  USERS_PROFILE_REQUEST: 'USERS_PROFILE_REQUEST',
  USERS_PROFILE_SUCCESS: 'USERS_PROFILE_SUCCESS',
  USERS_PROFILE_FAILURE: 'USERS_PROFILE_FAILURE',

  USERS_LOGOUT: 'USERS_LOGOUT',
};

export const jobsActionTypes = {
  JOBS_LIST_REQUEST: 'JOBS_LIST_REQUEST',
  JOBS_LIST_LOADED: 'JOBS_LIST_LOADED',
  JOBS_LIST_LOAD_FAILED: 'JOBS_LIST_LOAD_FAILED',
  JOBS_DETAILS_LOADED: 'JOBS_DETAILS_LOADED',
  JOBS_DETAILS_LOAD_FAILED: 'JOBS_DETAILS_LOAD_FAILED',
  JOBS_DETAILS_LOAD_REQUESTED: 'JOBS_DETAILS_LOAD_REQUESTED',

};

export const alertActionsTypes = {
  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_ERROR: 'ALERT_ERROR',
  ALERT_HIDE: 'ALERT_HIDE'
};
